//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExportWarehouse()
        {
            this.DetailExportWarehouses = new HashSet<DetailExportWarehouse>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> WarehouseID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailExportWarehouse> DetailExportWarehouses { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
