//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailExportWarehouses = new HashSet<DetailExportWarehouse>();
            this.DetailImportWarehoses = new HashSet<DetailImportWarehose>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public string Image { get; set; }
        public string Status { get; set; }
        public Nullable<long> WarehouseID { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailExportWarehouse> DetailExportWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailImportWarehose> DetailImportWarehoses { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
